### PR TITLE
add removeNullStrings function

### PR DESCRIPTION
**Pull request by yinxin630**

### CODE REVIEW

**Comment by dleitee** [comment]
Can you add this method on README.md?

**Comment by yinxin630** [comment]
ok, I will add it

**Comment by Kingwl** [comment]
oh it's very helpful for me

**Comment by zapline** [comment]
oh it's very helpful for me

**Comment by dleitee** [comment]
Hey @yinxin630 , thank you. Your pull request will be included in version 1.2.0.

**Comment by hustcer** [comment]
Would it be better if we name it as `removeEmptyStrings`? 😃

**Comment by dleitee** [comment]
I liked the name, and you @yinxin630 ?

**Comment by yinxin630** [comment]
@dleitee  yes, I think so. I will to modify it

**Pull request merged**
