### PR TITLE
Feature: Add rollup to build entire project.

### PR DESCRIPTION
**Pull request by dleitee**
Related issue: #78 

- [x] Build main file with rollup.
- [ ] Build all functions with rollup

### CODE REVIEW

**Comment by dleitee** [comment]
@phsetti @rodolfolottin @gdevincenzi 
someone of you wanna contributes here?

**Comment by phsetti** [comment]
I will

**Comment by dleitee** [comment]
Thanks, @phsetti to change the strman's CI from TravisCI to CircleCI.

**Comment by dleitee** [comment]
We still need to 
- [ ] Build All functions using Rollup

Someone of you wanna contribute with it? @gdevincenzi @phsetti @rodolfolottin

**Pull request closed without merging**
